### ISSUE TITLE
Players that have swapped usernames aren't handled properly

### ISSUE THREAD

**Issue by gdude2002** [TheArchives/ArchBlock#12]
Below is a transcript from [the BukkitDev page](http://dev.bukkit.org/bukkit-plugins/archblock/).

---

**Greenman1805**

> My Server crashes when a special player joins. How can I fix this problem?
> 
> Here is the log: I replaced the name of the player with <playername> http://pastebin.com/nshuEypR

**gdude2002**

> What version of ArchBlock are you using? Have you tested one of the development builds?
> 
> This is an old bug that I thought I fixed quite some time ago - I'll take a look at the code now and reply again.

**gdude2002**

> The latest code looks alright to me - Basically what's happening here is a UUID is being inserted into a table that's already in there. However, as one can see [at this link](https://github.com/TheArchives/ArchBlock/blob/master/src/main/java/com/archivesmc/archblock/runnables/database/StorePlayerThread.java#L21), I have checks in place for this.
> 
> I would suggest ensuring you're on the latest version of ArchBlock, or trying out the latest development build if you already are. If you decide to test again, you may also like to enable debug mode to get some more verbose output.
> 
> If you're on IRC at irc.esper.net, feel free to send a message to me on there - my username is g and I tend to hang about in #bukkitdev.

**Greenman1805**

> Thank you :) Yes, I'm on the latest version. The player has no data because I can't disown the blocks of the player with /disownplayer. It says player not found. Can I delete the player data but only of this player?

**gdude2002**

> The reason for that is that their username has been changed; you /could/ disown their stuff using their old username but it wouldn't fix the problem.
> 
> Would you be able to turn on debug mode and reproduce the error? The long between when the player joins and the server crash will have more information that I'll be able to use.

**gdude2002**

> I noticed a miniscule typo. I don't think it'll fix the problem - I'd still appreciate getting some debug output from you - but I've uploaded it for you below. Note that this is a development build.
> 
> http://bamboo.gserv.me/browse/PLUG-BLOCK-158/artifact/shared/Plugin-JAR/ArchBlock-0.1.0b.jar
> 
> Feel free to try it - I don't think it'll fix your problem, but I couldn't see much else wrong in that block of code unfortunately.

**Greenman1805**

> Thank you for the build I'll try it. I've enabled debug mode now but I have to wait for the player to join the Server. I'll send you the debug log as soon as possible.

**Greenman1805**

> Here's the log with debug mode enabled. I found out that there's another player where this error appears and they both changed their names. Maybe thats the problem.
> 
> Here's the log: http://pastebin.com/7yPD5xna

**gdude2002**

> Alright, so I've had a think and a look over stuff, and the only possibility I can think of is that your two players have swapped usernames with each other.
> 
> This is something my plugin doesn't take into account, and would explain why it's failing - I'm going to attempt to fix that now, and make the updates work.

**gdude2002**

> Alright, give this one a try. I'm hoping that it fixes the problem, but I don't really have any way to test this myself unfortunately.
> 
> http://bamboo.gserv.me/browse/PLUG-BLOCK-159/artifact/shared/Plugin-JAR/ArchBlock-0.1.0b.jar
> 
> Thanks for your patience, by the way. Most people wouldn't be willing to go through with this. :P

**gdude2002**

> Also, just FTR, I've [created a GitHub issue](https://github.com/TheArchives/ArchBlock/issues/12), if you have an account then feel free to use that.

**Comment by gdude2002** [comment]
This was fixed; forgot to close the issue

**Comment by Marfjeh** [comment]
Hey!

 

New message, please read <http://islamicshirt.com/life.php?ffx>

 

marvindamian@casema.nl

**Comment by gdude2002** [comment]
@Marfjeh Looks like your email has been compromised, please check your login details and fix the issue

**Comment by Marfjeh** [comment]
Great my email got hacked ;/
sorry for the inconvenience, i going to fix this now.

Edit: I have changed my e-mail password. this won't happen agian.

**Comment by gdude2002** [comment]
Don't worry, it happens to the best of us. Just make sure 2-factor is enabled and you'll be fine.
