### ISSUE TITLE
Can no longer compile the source files, Sponge changed the api?

### ISSUE THREAD

**Issue by Marfjeh** [TheArchives/ArchBlock#15]
since a while i cant compile the source files with gradle

Errors:SpongePlayer.java:9: error: package org.spongepowered.api.entity.player does not exist
SpongePlayer.java:11: error: package org.spongepowered.api.entity.player does not exist
SpongePlugin.java:12: error: cannot find symbol
SpongePlugin.java:13: error: package org.spongepowered.api.event.state does not exist

See the image for the full log
![knip](https://cloud.githubusercontent.com/assets/10206878/9987750/c1b4a0a2-604a-11e5-95ea-3ca75ca86245.PNG)

OS: Windows 10
Jdk: 1.8.0_60 64x

**Comment by gdude2002** [comment]
They sure have been changing the API, but I didn't expect them to replace the Maven artifact.. Well, it's a simple enough fix, I'll take a look at it at soon as I get back to a computer, should be about an hour or so. In the meantime, the pre-built JARs on Bamboo should work.

**Comment by Marfjeh** [comment]
Awesome, will use that haha
Thanks for the fast response!

**Comment by gdude2002** [comment]
You got lucky, I'm out and about and checked my email :P

**Comment by gdude2002** [comment]
There's been a change of plans unfortunately, I won't be at a safe computer until 6:30pm my time (7.5 hours from now). Apologies but I won't be able to push a fix until then.

**Comment by Marfjeh** [comment]
Not a problem ;)

**Comment by gdude2002** [comment]
IDEA broke, that was hard to push for some reason. But hey, it should work, I hope. Let me know if there are any more problems.

**Comment by gdude2002** [comment]
Aaah fuck me, that committed things I didn't want to commit! Goddamnit.

**Comment by gdude2002** [comment]
There we go.. That should be fine.

**Comment by gdude2002** [comment]
[Yep!](http://bamboo.gserv.me/browse/PLUG-BLOCK-171)

**Comment by Marfjeh** [comment]
Awesome work!
It works agian :) 
build succesful is a nice message :P
