### ISSUE TITLE
Idea: plugin multi-language support?

### ISSUE THREAD

**Issue by Marfjeh** [TheArchives/ArchBlock#7]
Hi This is not a issue but a suggestion for this great plugin, 

As you know (or not) i forked this plugin, only reason for translating, outside the small changes

Maybe its a great idea if it had multi-language support for other languages to make this plugin more awesome! 
If you want to do it, or I want to be the Dutch translator (if you wish)

**Comment by gdude2002** [comment]
I'm looking into this as we speak. Adding multiple language support shouldn't be that difficult; especially since Java has built-in support for it.

If you want to do the Dutch translations, that'd be fantastic. I'll get back to you when I've sorted something out.

**Comment by Marfjeh** [comment]
Awesome! :+1:  :D

**Comment by gdude2002** [comment]
Are you familiar with using resource bundle properties for this? The files look something like this..

![](http://i.imgur.com/BadJvmE.png)

**Comment by Marfjeh** [comment]
I'm new to this but i will find out how, 
it should do the tick Great work!

**Comment by gdude2002** [comment]
Here's an example file for you to look at. I know, it's kind of daunting, but there it is.

I'm working on making the plugin actually use the file now, I'll update this issue when that's done.

(File snipped, see the actual file [here](https://github.com/TheArchives/ArchBlock/blob/master/src/main/resources/translations/Messages.properties)).

**Comment by Marfjeh** [comment]
Like it!
I will start today for it, if it's ready i post it here ok? :)

**Comment by gdude2002** [comment]
Alright, but that's not the final file, wait for me to commit that first.

**Comment by gdude2002** [comment]
I've committed untested localization support! I was hoping to try it out on my test server, but I [can't build the plugin right now](http://bamboo.gserv.me/browse/PLUG-BLOCK-140) as the Spigot maven repo is down, and I need libraries from there to compile it.

![](http://i.imgur.com/hTMOueL.png)

**Comment by gdude2002** [comment]
[Looks like it's building now](http://bamboo.gserv.me/browse/PLUG-BLOCK-141), I'll give it a quick test.

**Comment by gdude2002** [comment]
Alright, @Marfjeh, it appears to work. If you want to supply a translation, fork this repo, head over to the [translation resources](https://github.com/TheArchives/ArchBlock/tree/master/src/main/resources/translations) and make a copy of `Messages.properties`, naming it `Messages_<language>.properties`. For example, since you're working with Dutch, you might call it `Messages_nl.properties`.

When you're done, submit a [Pull Request](https://github.com/TheArchives/ArchBlock/pulls) for review.

**Comment by gdude2002** [comment]
There appears to be a few people that might like to do translations, btw. So it's nice that this idea will be used by more than one person \o/

**Comment by Marfjeh** [comment]
Alright i will doing it today, sorry for not responding for 2 days there's was a Gas leak in my house soo yeah... haha its been fixed, and i will make the translations. Great work! :D

**Comment by Marfjeh** [comment]
EDIT: I've made a second fork for the plugin for the dutch translation file it is indeed called "Messages_nl.properties" i will do a pull request if i'm done.

**Comment by gdude2002** [comment]
It's all good.

I think someone else is also doing a Dutch translation, so we'll see who gets there first :P

It'd be good to have multiple, to check for correctness, anyway.

**Comment by Marfjeh** [comment]
I'm done, i will request a pull request.

**Comment by gdude2002** [comment]
Gotcha.

**Comment by gdude2002** [comment]
Okay, I've made a release on BukkitDev and SpigotMC. Feel free to download it!

I'm going to close this ticket now, and look at making another one for other languages.
